name: "CI for Pull Requests"

on:
  pull_request:

concurrency:
  group: tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-unit-tests:
    uses: ./.github/workflows/unit_tests.yml
  
  run-docker-tests:
    uses: ./.github/workflows/docker_tests.yml
