name: Tests

on:
  workflow_call:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      
      - name: Lint
        run: deno run lint
      
      - name: Fromat check
        run: deno run format
      
      - name: Test
        run: deno run test
